name: Node.js

on:
  push:
    branches:
      - main
  pull_request:

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      # Enable Corepack before setting up Node.js
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies 📦
        run: yarn install

      - name: Run prettier check
        run: yarn prettier

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Generate Typechain types
        run: yarn typechain

      - name: Run hardhat tests
        run: yarn test:hardhat
